steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/gesp-459003/docker-repo/fallertrack-api",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/gesp-459003/docker-repo/fallertrack-api",
      ]

images:
  - "us-central1-docker.pkg.dev/gesp-459003/docker-repo/fallertrack-api"
